### ISSUE TITLE
I could not find the data folder, eacl-appendix-code and eacl-ued-code. 

### ISSUE THREAD

**Issue by TianlinZhang668** [whipson/edyn#1]
Hi, I could not find the data folder, eacl-appendix-code and eacl-ued-code. Could you provide these files? thank you

**Comment by whipson** [comment]
Hello,

Sorry about this. I added the notebooks (.Rmd). Turns out Github's size restrictions won't allow me to upload all the data. I uploaded imsdb.csv which contains the unlemmatized utterances.
